"use client"
import TitleHandler from '@/components/TitleHandler';
import React from 'react';
import { usePathname } from 'next/navigation';
import { ArrowLeft } from 'lucide-react';

const glossaryItems = [
    { term: 'Emission Offsetting', 
        definition: 'The pursuit of neutralising CO2 emissions emitted by a person, client, or organisation. It is achieved through the purchase of carbon credits: There are two main projects through which carbon credits are obtained, ABSORPTION projects, such as reforestation or blue carbon (marine biodiversity podinia), and AVOIDANCE projects, such as the use of renewable energy or biomass transformation, which avoid emissions. All projects must be certified, either nationally or internationally, and can be public or private: National - Public: MITECO National - Private: Cercarbono (Colombia) International - Public: UN International - Private: Verra or Golden Standard. There are two main reasons companies seek to offset their emissions: communication and obtaining the highest score in bid tenders.' },
    { term: 'Energy Efficiency', 
        definition: 'Optimising energy use to achieve the same level of well-being by adapting consumption to actual needs or implementing energy-saving systems. Energy efficiency ensures a stable supply for an entire population or supply chain. One of the most used international frameworks for measuring energy efficiency is ISO 50001.' },
    { term: 'Emission Factor', 
        definition: 'Emission factors refer to numerical values representing the amount of pollutants or greenhouse gases released into the atmosphere per unit of activity or production. These factors are used to calculate and estimate total emissions generated by various sources, such as industries, vehicles, combustion processes, and energy generation. Emission factors are essential in evaluating and managing atmospheric pollution and climate change.' },
    { term: 'Environmental Rights', 
        definition: 'A set of international and regional standards established from 1970 in response to environmental disasters like Chernobyl. They are based on three fundamental pillars: preventing negative environmental impact, ensuring sustainable development, and penalising harmful practices.' },

    ];

const E = () => {
    const pathname = usePathname()

    return (
        <div className='min-h-screen flex flex-col justify-between ml-0 p-6 lg:ml-64'>
            <div>
                <div className='flex items-center mb-4 gap-2'>
                    <button onClick={() => window.history.back()} className='flex items-center gap-2 text-blue-600 hover:text-blue-800'>
                        <ArrowLeft className='w-6 h-6' /> 
                    </button>
                    <TitleHandler title="Glossary" text='E' />
                </div>
                <div className='flex gap-10 flex-wrap mt-4 h-full w-full pb-9 flex-col lg:flex-row'>

                    {glossaryItems.map((item, index) => (
                        <div key={index} className='relative bg-white shadow-xl px-7 py-5 rounded-xl w-[350px] flex-grow'>
                            <div className='flex flex-col mb-5'>
                                <h1 className='font-bold text-neutral-700 text-2xl Geometos'>{item.term}</h1>
                                <p className='text-neutral-600 mt-2'>{item.definition}</p>
                            </div>
                            <div className='border-t border-gray-300 mt-4'></div>
                        </div>
                    ))}

                </div>
            </div>
        </div>
    );
}

export default E;
