"use client"
import TitleHandler from '@/components/TitleHandler';
import React from 'react';
import { usePathname } from 'next/navigation';
import { ArrowLeft } from 'lucide-react';

const glossaryItems = [
    { term: 'Carbon Capture', 
        definition: 'The process of capturing and storing carbon dioxide from the atmosphere. Carbon dioxide can be stored underground in what is called geological sequestration for geologically significant periods. Carbon dioxide can also be stored short-term by plants, water, and soil in a process called biogenic sequestration.' },
    { term: 'Carbon Dioxide Equivalent (CO2e)', 
        definition: 'Carbon Dioxide Equivalent (CO2e) is the unit of measure for the warming effect of greenhouse gases. CO2e is the rate at which other greenhouse gases convert to carbon. The rate of change expresses how many kilograms of carbon dioxide emissions warm the climate equally as 1 kg of another greenhouse gas over a certain period (commonly 100 years). CO2e allows us to compare and equate the impact of different greenhouse gases in a single climate footprint.' },
    { term: 'Carbon Negative', 
        definition: 'Certification achieved by offsetting double the equivalent CO2 emissions associated with human, corporate, or national activities. This not only compensates for the impact of human activities but also generates a positive impact on the environment by removing additional CO2 from the atmosphere.' },
    { term: 'Carbon Neutral', 
        definition: 'Certification achieved by offsetting the equivalent amount of CO2 emissions associated with human, corporate, or national activities. In this way, the CO2 emissions generated by these activities are avoided through financing clean energy projects or carbon sinks.' },
    { term: 'Climate Change', 
        definition: 'Refers to the alteration of Earth is climate compared to its historical global and regional record. Various natural and anthropogenic factors cause it, including global warming or ozone layer depletion.' },
    { term: 'Conference of the Parties (COP)', 
        definition: 'The Conference of the Parties (COP) is the annual meeting of the parties to the United Nations Framework Convention on Climate Change (UNFCCC) to assess the global status of climate change. The Paris Agreement, an international treaty on climate change, was adopted at the 2015 COP. Each COP since then has also served as a meeting of the parties to the Paris Agreement to develop the agreement is rules and monitor its implementation and results.' },

    ];

const C = () => {
    const pathname = usePathname()

    return (
        <div className='min-h-screen flex flex-col justify-between ml-0 p-6 lg:ml-64'>
            <div>
                <div className='flex items-center mb-4 gap-2'>
                    <button onClick={() => window.history.back()} className='flex items-center gap-2 text-blue-600 hover:text-blue-800'>
                        <ArrowLeft className='w-6 h-6' /> 
                    </button>
                    <TitleHandler title="Glossary" text='C' />
                </div>
                <div className='flex gap-10 flex-wrap mt-4 h-full w-full pb-9 flex-col lg:flex-row'>

                    {glossaryItems.map((item, index) => (
                        <div key={index} className='relative bg-white shadow-xl px-7 py-5 rounded-xl flex-grow w-[350px]'>
                            <div className='flex flex-col mb-5 '>
                                <h1 className='font-bold text-neutral-700 text-2xl Geometos'>{item.term}</h1>
                                <p className='text-neutral-600 mt-2'>{item.definition}</p>
                            </div>
                            <div className='border-t border-gray-300 mt-4'></div>
                        </div>
                    ))}

                </div>
            </div>
        </div>
    );
}

export default C;
